dpc-sdp/dev-tools

composer.dev.json

This PR moves the Drupal version that Tide is working with to `8.6.12` and will be tested in conjunction with JSONAPI upgrades.

Update Drupal to 8.6.12

---

composer.json
scripts/drupal/deploy.sh

command "drush search-api-index 0 50" doesn't work.
after removing the parameters , it works.

udpated deploy.sh

---

composer.dev.json
composer.json

1. Updates reference to behat/gherkin patch so it applies to 4.6.0

Update gherkin patch

---

composer.dev.json

dpc-sdp/content-vic-gov-au#780

Bumped PHP version Composer config.

---

composer.dev.json

https://digital-engagement.atlassian.net/browse/SDPA-3932
1. remove 
```
"patches": {
"behat/gherkin": {
"Correctly filter features, now that the base path is correctly set": "https://github.com/Behat/Gherkin/compare/v4.6.0...a7d84eb6ba245ea268a304312d14660788bf6c29.patch"
}
}
```
2. more details see https://github.com/Behat/Gherkin/blob/v4.6.1/CHANGES.md

[SDPA-3932] remove the patch

---

composer.dev.json

On-behalf-of: @salsadigitalauorg <sonny@salsadigital.com.au>

Temporarily pinned Drush to 8.3.2.

---

composer.dev.json
composer.json

https://digital-engagement.atlassian.net/browse/SDPA-4225
1. bumped `drupal/core` to 8.8.6
https://github.com/dpc-sdp/content-vic-gov-au/pull/867

[SDPA-4225] updates dev-tools to be compatible with Drupal 8.8.5

---

composer.dev.json

https://digital-engagement.atlassian.net/browse/SDPA-4613
1. upgrades drupal core to 8.8.10

[SDPA-4613] upgrade drupal core to 8.8.10

---

composer.dev.json

https://digital-engagement.atlassian.net/browse/SDPA-4830
1. upgrade core to 8.8.x (8.8.11)

[SDPA-4830] upgrade to 8.8.x

---

composer.dev.json
phpcs.xml
tests/behat/bootstrap/FeatureContext.php
tests/behat/bootstrap/TideEntityTrait.php
tests/behat/bootstrap/TideExtensionsTrait.php

On-behalf-of: @salsadigitalauorg <sonny@salsadigital.com.au>

Pumped PHP minimum version to 7.3 so that other modules could use new features without failing code linting and Added more test traits.

---

composer.dev.json
composer.json

https://digital-engagement.atlassian.net/browse/SDPA-4790

[SDPA-4790] update to use drupalcore 8.9.x

---

tests/behat/bootstrap/FeatureContext.php

Added JSTrait to give access to `When /^(?:|I )click (an?|on) "(?P<element>[^"]*)" element$/` for testing clone confirmation submission form.

[SDPA-4755] Added JSTrait

---

tests/behat/bootstrap/TideCommonTrait.php

On-behalf-of: @salsadigitalauorg <sonny@salsadigital.com.au>

Added more behat test steps to common test trait.

---

composer.dev.json

Added packages that are defined in tide_webform

[DDS-901] Added packages that are defined in tide_webform.

---

scripts/composer/DrupalSettings.php

On-behalf-of: @salsadigitalauorg <sonny@salsadigital.com.au>

Allowed installing extensions under tests directory.

---

composer.dev.json
composer.json

1) Added Drupal Test Traits to Dev Tools.
2) Bump tide_core to 3.0.0.

[SDPA-5674] Add Drupal Test Traits

---

composer.dev.json
scripts/composer/DrupalSettings.php

Update phpdotenv to version 4.1 to support the php-jira-rest library.

[SDPA-5674] Update phpdotenv to 4.1

---

composer.dev.json
composer.json
tests/behat/bootstrap/FeatureContext.php

https://digital-engagement.atlassian.net/browse/SDPA-5826
Added Visibility test trait to support a test case
Related test case update in tide_core 
https://github.com/dpc-sdp/tide_core/pull/281

Added visibility test trait.

---

composer.json
tests/behat/bootstrap/TideCommonTrait.php

Jira: https://digital-engagement.atlassian.net/browse/SDPA-5327
Related PR's: https://github.com/dpc-sdp/tide_core/pull/293/files
Changes
1) Add function to find menu item text matching a given text

[SDPA-5327] Add find menu item function

---

composer.json

1. changes tide_core from reference "3.0.0" to "^3.0.0"

Bumps tide_core to latest

---

composer.dev.json
composer.json

Jira: https://digital-vic.atlassian.net/browse/SRM-512
Changes:
1.

Feature/srm 512 update drupal to 9.4

---

composer.dev.json

Update core-dev to 9.5.x

---

patches/ckeditor_templates/ckeditor_templates_4.patch
patches/embed/issues_3309747.patch
patches/video_embed_field/video_embed_field_6.patch

When working on this ticket https://digital-vic.atlassian.net/browse/SDPAP-7477
New local patches are being used in tide_core and tide_media  as a ck5 updates and tide_api requires tide_core so those patches are being added in this pr to fix the issue in tide modules.

[SDPAP-7477]adding ck editor patch

---

.ahoy.yml

**Changes**
Jira : https://digital-vic.atlassian.net/browse/SRM-952
1. Add ahoy command in `ahoy.yml` template to fix php linting errors

[SRM-952] Add ahoy command to fix lint errors

---

tests/behat/bootstrap/TideCommonTrait.php

Add iWaitForTheBatchProcessToFinish detecting when the batch process is finished in our behat test.

Add iWaitForTheBatchProcessToFinish detecting when the batch process is finished

---

composer.dev.json

https://digital-vic.atlassian.net/browse/SD-29

[SD-29] Upgrade dev-tools to compatible with Drupal to 10.3.x
