dpc-sdp/dev-tools

.ahoy.yml
.env

`PROJECT_NAME` should not be changed from how it actually been specified. It had erroneous  code to strip underscores in order to make the local dev URL to not contain underscores.
As a byproduct of this - the docker compose project name was affected as well, resulting in all containers having underscores stripped, which is not a standard behaviour of docker compose (it just uses the dir name): `tide_api` would become `tideapi`.
This PR addresses this problem and applies stripping of underscore only for URL.
It also adds replacement of the space character with hyphen in URL.
The test build of the project that uses this change is here
https://circleci.com/workflow-run/583e1ca3-315c-4ee8-a115-55f5865d98ba

Fixed project name not correctly handling underscores and hyphens.

---

.ahoy.yml
composer.dev.json
scripts/composer/ScriptHandler.php

- Fixed composer script handler not correctly working with settings files when provisioned inside of the container. This leads to inability to install projects with `ahoy build` from the first time.
Test build for this change from `tide-page` module https://circleci.com/workflow-run/8fd39a99-12a0-443c-984c-c61744371b4e

Fixed composer scripts.

---

.ahoy.yml

Small, but important change.
Without this change, when changing the branch and running `ahoy build` that would generate new `composer.build.json` with new dependencies, `composer.build.lock` was not removed making composer install  different (previous) dependencies that were in `composer.build.json`.

Fixed clean command not removing temp composer files.

---

.docker/Dockerfile.cli
.docker/Dockerfile.php

steps I removed from these 2 docker files have been implemented in parent images:
https://github.com/dpc-sdp/bay/blob/master/bay/images/Dockerfile.builder
https://github.com/dpc-sdp/bay/blob/master/bay/images/Dockerfile.php
adding below step to the cli docker file :
ADD dpc-sdp /app/dpc-sdp
otherwise composer will not be able to find the dpc-sdp package

removed steps that have been implemented in parent images

---

docker-compose.yml

https://medium.com/@alex.designworks/chromedriver-75-enforces-w3c-standard-breaking-behat-tests-460cad435545

Pinned Chrome image to v74.

---

composer.dev.json

`1.3.x-dev` branch of `behat/mink-selenium2-driver` has been superseded by `1.4.x-dev`. This change grabs the latest available version of the 1.3 branch.

Update dev-require for behat/mink-selenium2-driver

---

.circleci/test-artifacts.sh

If a project's test profile doesn't define any tests `ahoy test-behat` will not create the screenshots directory and the `.circleci/test-artifacts.sh` script will cause the CI step "Copy artifacts" to fail
1. Added a conditional check for the presence of the screenshots directory.

Added conditional check for screenshot dir

---

composer.dev.json

Composer packages.drupal.org definition incorrect for `drupal/coder` 8.3.9
1. https://www.drupal.org/project/coder/issues/3134853#comment-13606973

fix drupal coder issue

---

composer.dev.json

https://digital-engagement.atlassian.net/browse/SDPA-4334
Added CKeditor list-style repository for tide_core to pass the build.
https://github.com/dpc-sdp/tide_core/pull/184

[SDPA-4334] Added ckeditor lisstyle plugin repository.

---

composer.dev.json

https://digital-engagement.atlassian.net/browse/SDPA-4745
1. pin `squizlabs/php_codesniffer` to 3.5.6 to avoid lint errors.
```bash
==> Lint code
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function DrupalPractice\Sniffs\CodeAnalysis\ScopeInfo::__construct(), 0 passed in /app/vendor/squizlabs/php_codesniffer/src/Ruleset.php on line 1209 and exactly 1 expected in /app/vendor/drupal/coder/coder_sniffer/DrupalPractice/Sniffs/CodeAnalysis/VariableAnalysisSniff.php:49
Stack trace:
#0 /app/vendor/squizlabs/php_codesniffer/src/Ruleset.php(1209): DrupalPractice\Sniffs\CodeAnalysis\ScopeInfo->__construct()
#1 /app/vendor/squizlabs/php_codesniffer/src/Ruleset.php(218): PHP_CodeSniffer\Ruleset->populateTokenListeners()
#2 …
```

pin 'squizlabs/php_codesniffer' to 3.5.6

---

composer.json

As there were some breaking changes in tide_core, now the tide_core is bumped up to 2.0.0. Because of this change, the version of tide_core needs to be updated here.

[bump_up_tide_core] Upgraded tide_core.

---

.circleci/test.sh
README.md
composer.dev.json
composer.json
phpunit.xml.dist

1. we would like standardised unit tests for our modules, we raised this requirement in a dev meeting in last year.
2. it is part of my PDP 😬 
actual unit tests should reside in each tide_* modules.
ok, it runs under CI. 
it is ready to roll out to all tide_* modules. and this update focuses `unit` test only.

Adds phpunit to dev-tools

---

composer.dev.json

This needs to be added in dev-tools, else the tide modules that are dependant on tide_core fails in CI.
Also, all the packages need to be removed from tide_core and release tasks might be needed to add it in the root composer.

[DDS-901] Updated package.

---

phpcs.xml

1) Update linting to PHP 7.4 feature level.
```
[tide_core]cli-drupal:/app$ php -v
PHP 7.4 (cli) (built: Aug 27 2021 21:53:25) ( NTS )
```

[SDPA-5674] Update to PHP 7.4 feature level

---

.ahoy.yml

- Append `--no-browser` to the `drush user:login` command permanently
- Rewrite the `ahoy login` one-liner to unblock user 1 
The Drush command syntax has changed since this Ahoy command was created. The proposed change will work with Drush 9 and Drush 10+
- fixes #67

Update ahoy login command for Drush 10

---

composer.dev.json

Reference to this conversation - https://github.com/dpc-sdp/content-vic-gov-au/pull/1380#discussion_r882248359
Apparently if allow-plugins is not added by July 2002 then Composer will stop loading plugins altogether. This would stop Drupal installing properly.
It was added for all projects root composer but it needs to be added here to pass the build for all tide modules.
It causes build fail in CI reference - https://app.circleci.com/pipelines/github/dpc-sdp/tide_media/316/workflows/0d6a8a67-4f4e-4d93-ac17-6683798c6057
After using this dev-tools commit reference it passes the build - https://app.circleci.com/pipelines/github/dpc-sdp/tide_media/317/workflows/6d417123-c6d6-4aa2-9f34-aee79ac8b4a6

Added composer changes.

---

.circleci/config.yml
.docker/Dockerfile.cli
.docker/Dockerfile.nginx-drupal
.docker/Dockerfile.php
composer.dev.json
docker-compose.yml
phpcs.xml
scripts/composer/DrupalSettings.php

Added updates related to php 8.1 and use the latest bay image version
I have used this PR to build this tide_core PR and it resolves the new lint issues as well. 
https://github.com/dpc-sdp/tide_core/pull/357

Updated bay image version to 5.x.

---

.ahoy.yml
.circleci/build.sh
.circleci/config.yml
.docker/Caddyfile
.docker/Dockerfile.cli
.docker/Dockerfile.elasticsearch
.docker/Dockerfile.nginx-drupal
.docker/Dockerfile.php
.docker/elasticsearch.ci.yml
.docker/elasticsearch.yml
README.md
composer.dev.json
docker-compose.yml

Required so that all tide libs can pull in the latest dev stack for building.

Update dev stack for all tide libraries that still use dev tools

---

composer.dev.json
composer.json

https://digital-vic.atlassian.net/browse/SRM-797
Drupal 9.4.x is end of life on June 21, 2023.
Update drupal/core to `9.5.x`

Update drupalcore to 9.5.x

---

tests/behat/bootstrap/FeatureContext.php

While working on https://digital-vic.atlassian.net/browse/SDPAP-7655
I got CI test errors that the Use statements should be sorted alphabetically.

[SDPAP-7655] Use statements sorted alpha

---

.ahoy.yml

As per discussion in slack, missing these variables causes the following build issue in tide modules:
```
=> CANCELED [tide_core 8/8] RUN echo "memory_limit=-1" >> /usr/local/etc/php/conf.d/memory.ini     && COMPOSER=composer.build.json composer install -n --no-dev --ansi --prefer-dist --no-suggest --optimiz  3.7s
------
> [tide_core-php internal] load metadata for docker.io/library/tide_core:latest:
------
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

Add missing docker variables in dev-tools for ahoy config

---

docker-compose.yml

`host.docker.internal` is wildly inconsistient in my tests with Colima, but the host IP will always be fixed to this IP in the Colima stack, so this is fine.
Tested with tide_search and it works as expected.

Update dockerhost to be compatible with colima for xdebug

---

composer.dev.json

A new version compatible with D10 is released.
https://www.drupal.org/project/password_strength/releases/8.x-2.0-beta3

Removed password strength fork reference from composer dev.

---

behat.yml
composer.dev.json
tests/behat/bootstrap/TideCommonTrait.php

https://digital-vic.atlassian.net/browse/SDPAP-9261
We need to install mink browserkit behat package in dev-tools to avoid the test errors in tide modules as behat/mink-goutte-driver is abandoned and no longer maintained.

added mink browserkit driver
